    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Elastic APT GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Elastic APT repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Elastic Stack
      apt:
        name: 
          - elasticsearch
          - kibana
          - logstash
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Kibana
      service:
        name: kibana
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Logstash
      service:
        name: logstash
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

